In [1]:
import pandas as pd
import numpy as np

In [2]:
from scipy.stats import zscore
from sklearn.preprocessing import Imputer
from sklearn.metrics import accuracy_score
from sklearn import metrics

In [3]:
des=pd.read_excel("diabeticdata.xlsx",sheet_name=0)
des

                Variable                                        Description
0             patient_id  Patient identification number,unique for each ...
1            line1stdate                               treatment start date
2            line2stdate                              treatment change date
3                    age          age of patient as on traetment start date
4                 gender                                  gender of patient
5               agegroup                               age group of patient
6                   sbpn                               systolic diapressure
7                   dbpn                                 diastolic pressure
8          smokingstatus                                     smoking status
9            Diseasecode                                       disease code
10          hospitalsize                 hospital size the patient admitted
11       durationofline1  duration of traetment start to traetment chang...
12  line1drugcombination  drug combination type during treatment start a...
13  line2drugcombination      drug combination type after treatment change
14            line1drugs  drugs used  during treatment start and treatme...
15            line2drugs                drugs used  after treatment change
16            curestatus           status of disease cure (target variable)

In [4]:
data=pd.read_excel("diabeticdata.xlsx",sheet_name=1)
data

,patient_id,line1stdate,line2stdate,age,gender,agegroup,sbpn,dbpn,smokingstatus,Diseasecode,hospitalsize,durationofline1,line1drugcombination,line2drugcombination,line1drugs,line2drugs,curestatus
0,MB0001,2010-06-19,2010-07-19,26.746064,Male,20 – 34 years,109.0,63.0,Non-smoker,D1,More then 450 Number of beds,1,Unfixed,Unfixed,Drug2,Drug3+Drug2,0
1,MB0002,2014-12-19,2015-02-19,54.332649,Male,50 - 64 years,119.0,87.0,Current smoker,D6,1-50 number of beds,2,Unfixed,Unfixed,Drug3,Drug3+Drug2,1
2,MB0003,2011-07-20,2011-09-20,47.249829,Female,35 – 49 years,110.0,64.0,Non-smoker,D6,1-50 number of beds,2,Unfixed,Unfixed,Drug3,Drug3+Drug2,1
3,MB0004,2017-07-29,2017-08-05,63.028063,Female,50 - 64 years,140.0,84.0,NaN,D2,1-50 number of beds,0,Unfixed,Unfixed,Drug5,Drug1+Drug5,1
4,MB0005,2010-10-19,2014-03-19,48.082136,Female,35 – 49 years,157.0,96.0,Non-smoker,D6,More then 450 Number of beds,41,Unfixed,Unfixed,Drug3,Drug3+Drug2,0
5,MB0006,2016-07-07,2016-08-27,71.797399,Female,≥ 65 years,NaN,NaN,NaN,D6,1-50 number of beds,2,Unfixed,Unfixed,Drug2,Drug3+Drug2,0
6,MB0007,2014-06-22,2015-11-29,56.175222,Male,50 - 64 years,123.0,82.0,Non-smoker,D2,1-50 number of beds,17,Unfixed,Unfixed,Drug2,Drug3+Drug2,1
7,MB0008,2016-01-23,2016-04-16,58.513347,Female,50 - 64 years,NaN,NaN,NaN,D6,1-50 number of beds,3,Fixed,Fixed,Drug9,Drug9+Drug2,0
8,MB0009,2013-12-19,2015-12-30,51.000684,Male,50 - 64 years,NaN,NaN,NaN,D6,1-50 number of beds,24,Fixed,Unfixed,Drug10,Drug3+Drug2,1
9,MB0010,2016-11-29,2016-12-04,51.613963,Male,50 - 64 years,114.0,70.0,Non-smoker,D6,1-50 number of beds,0,Unfixed,Fixed,Drug3,Drug1+Drug9,0
10,MB0011,2014-07-19,2017-01-26,48.249144,Male,35 – 49 years,134.0,88.0,Non-smoker,D2,1-50 number of beds,30,Unfixed,Unfixed,Drug2,Drug2,0
11,MB0012,2013-03-21,2017-01-25,65.752225,Male,≥ 65 years,138.0,80.0,Non-smoker,D2,351-450 number of beds,46,Unfixed,Unfixed,Drug2,Drug2,1
12,MB0013,2013-11-29,2014-09-13,40.279261,Male,35 – 49 years,107.0,59.0,Non-smoker,D1,351-450 number of beds,9,Unfixed,Fixed,Drug2,Drug9+Drug2,1
13,MB0014,2012-09-04,2014-12-10,50.130048,Male,50 - 64 years,NaN,NaN,NaN,D6,1-50 number of beds,27,Unfixed,Fixed,Drug2,Drug10+Drug2,0
14,MB0015,2015-08-09,2017-08-06,51.222450,Female,50 - 64 years,141.0,86.0,Non-smoker,D6,1-50 number of beds,24,Unfixed,Unfixed,Drug3,Drug5+Drug3,1
15,MB0016,2015-12-20,2016-10-01,50.001369,Malee,50 - 64 years,109.0,71.0,Current smoker,D6,1-50 number of beds,9,Unfixed,Unfixed,Drug3,Drug3+Drug2,0
16,MB0017,2016-06-04,2016-06-11,56.958248,Female,50 - 64 years,NaN,NaN,NaN,D2,1-50 number of beds,0,Unfixed,Unfixed,Drug2,Drug3+Drug4+Drug2,0
17,MB0018,2008-07-24,2008-11-25,36.095825,Female,35 – 49 years,NaN,NaN,NaN,D1,1-50 number of beds,4,Unfixed,Unfixed,Drug3,Drug3+Drug2,1
18,MB0019,2014-02-16,2017-02-05,56.410678,Male,50 - 64 years,128.0,88.0,Non-smoker,D6,1-50 number of beds,36,Unfixed,Unfixed,Drug3,Drug3+Drug2,1
19,MB0020,2016-12-22,2017-01-12,55.427789,Female,50 - 64 years,131.0,84.0,Non-smoker,D1,1-50 number of beds,1,Unfixed,Fixed,Drug1,Drug1+Drug9,0
20,MB0021,2017-07-22,2017-11-02,47.008898,Female,35 – 49 years,126.0,67.0,Non-smoker,D1,1-50 number of beds,3,Unfixed,Unfixed,Drug3,Drug5+Drug2,1
21,MB0022,2015-05-13,2015-07-12,33.645448,Male,20 – 34 years,NaN,NaN,NaN,D2,1-50 number of beds,2,Unfixed,Unfixed,Drug3,Drug2,0
22,MB0023,2015-10-23,2015-11-10,52.008214,Male,50 - 64 years,120.0,90.0,Current smoker,D6,1-50 number of beds,1,Unfixed,Unfixed,Drug2,Drug2,0
23,MB0024,2012-03-19,2013-01-19,53.415469,Male,50 - 64 years,124.0,81.0,Current smoker,D1,351-450 number of beds,10,Unfixed,Unfixed,Drug2,Drug5+Drug3,1
24,MB0025,2009-10-19,2011-04-20,38.833676,Female,35 – 49 years,NaN,NaN,NaN,D6,1-50 number of beds,18,Unfixed,Unfixed,Drug3,Drug3+Drug2,1
25,MB0026,2013-07-26,2016-01-16,57.932923,Female,50 - 64 years,140.0,87.0,Non-smoker,D1,More then 450 Number of beds,30,Unfixed,Unfixed,Drug2,Drug3+Drug2,1
26,MB0027,2014-09-04,2014-09-28,39.709788,Female,35 – 49 years,160.0,100.0,Non-smoker,D1,1-50 number of beds,1,Unfixed,Unfixed,Drug3,Drug3,0
27,MB0028,2015-09-19,2016-04-12,47.334702,Female,35 – 49 years,118.0,71.0,Non-smoker,D1,1-50 number of beds,7,Unfixed,Unfixed,Drug2,Drug3+Drug2,1
28,MB0029,2016-04-22,2016-05-06,66.507871,Female,≥ 65 years,NaN,NaN,NaN,D2,1-50 number of beds,0,Unfixed,Fixed,Drug2,Drug10+Drug2,0
29,MB0030,2016-04-26,2017-09-26,50.351814,Male,50 - 64 years,134.0,76.0,Non-smoker,D6,1-50 number of beds,17,Unfixed,Unfixed,Drug2,Drug2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1370,MB1371,2016-07-30,2017-02-03,62.611910,Male,50 - 64 years,140.0,100.0,Non-smoker,D2,1-50 number of beds,6,Unfixed,Unfixed,Drug2,Drug3+Drug2,0
1371,MB1372,2016-09-22,2016-09-30,60.925394,Female,50 - 64 years,NaN,NaN,NaN,D1,1-50 number of beds,0,Unfixed,Unfixed,Drug2,Drug3+Drug2,0
1372,MB1373,2017-09-05,2017-09-07,30.795346,Male,20 – 34 years,NaN,NaN,NaN,D6,More then 450 Number of beds,0,Fixed,Unfixed,Drug9,Drug1+Drug2,0
1373,MB1374,2015-07-29,2017-05-18,41.941136,Male,35 – 49 years,120.0,74.0,Non-smoker,D6,1-50 number of beds,22,Unfixed,Fixed,Drug2,Drug1+Drug10,0
1374,MB1375,2015-07-26,2016-03-17,53.018480,Male,50 - 64 years,138.0,83.0,Non-smoker,D1,More then 450 Number of beds,8,Unfixed,Unfixed,Drug6,Drug3+Drug2,0
1375,MB1376,2014-09-19,2016-01-30,41.169062,Female,35 – 49 years,96.0,56.0,Non-smoker,D1,1-50 number of beds,16,Unfixed,Fixed,Drug3,Drug9+Drug2,0
1376,MB1377,2014-12-19,2015-02-19,56.334018,Male,50 - 64 years,118.0,57.0,Non-smoker,D1,1-50 number of beds,2,Unfixed,Unfixed,Drug3,Drug4+Drug2,0
1377,MB1378,2011-05-20,2011-09-20,44.246407,Male,35 – 49 years,112.0,75.0,Non-smoker,D2,More then 450 Number of beds,4,Unfixed,Unfixed,Drug2,Drug3+Drug2,0
1378,MB1379,2016-08-14,2017-08-09,60.818617,Male,50 - 64 years,116.0,77.0,Non-smoker,D1,1-50 number of beds,12,Unfixed,Unfixed,Drug2,Drug2,1
1379,MB1380,2014-09-09,2017-06-06,64.309377,Male,50 - 64 years,146.0,72.0,Non-smoker,D2,1-50 number of beds,33,Unfixed,Unfixed,Drug2,Drug4+Drug2,1
1380,MB1381,2013-09-11,2016-11-01,40.558522,Male,35 – 49 years,129.0,89.0,Current smoker,D6,1-50 number of beds,38,Unfixed,Unfixed,Drug2,Drug4+Drug2,0
1381,MB1382,2011-08-20,2013-05-19,52.668036,Female,50 - 64 years,NaN,NaN,NaN,D4,251-350 number of beds,21,Unfixed,Unfixed,Drug3+Drug2,Drug3+Drug4+Drug2,0
1382,MB1383,2016-12-04,2017-05-04,40.208077,Male,35 – 49 years,132.0,74.0,Current smoker,D1,1-50 number of beds,5,Unfixed,Unfixed,Drug2,Drug1+Drug3,0
1383,MB1384,2013-12-28,2014-04-30,53.357974,Male,50 - 64 years,112.0,75.0,Non-smoker,D6,1-50 number of beds,4,Unfixed,Fixed,Drug2,Drug9+Drug2,0
1384,MB1385,2012-10-19,2016-08-10,43.252567,Male,35 – 49 years,NaN,NaN,NaN,D6,1-50 number of beds,46,Unfixed,Fixed,Drug2,Drug9+Drug2,0
1385,MB1386,2015-12-24,2016-12-03,65.514031,Female,≥ 65 years,NaN,NaN,NaN,D6,1-50 number of beds,11,Unfixed,Unfixed,Drug2,Drug2,0
1386,MB1387,2016-01-01,2016-01-23,51.786448,Female,50 - 64 years,NaN,NaN,NaN,D2,1-50 number of beds,1,Unfixed,Unfixed,Drug2,Drug2,0
1387,MB1388,2017-07-19,2017-09-06,35.082820,Male,35 – 49 years,NaN,NaN,NaN,D6,151-250 number of beds,2,Fixed,Fixed,Drug9,Drug9+Drug2,0
1388,MB1389,2016-03-23,2016-11-15,40.172485,Male,35 – 49 years,106.0,69.0,Non-smoker,D6,1-50 number of beds,8,Unfixed,Unfixed,Drug2,Drug4+Drug2,0
1389,MB1390,2012-03-02,2017-03-19,35.200548,Male,35 – 49 years,123.0,82.0,Non-smoker,D1,1-50 number of beds,61,Unfixed,Unfixed,Drug3,Drug2,0
1390,MB1391,2009-03-19,2014-09-19,47.915127,Female,35 – 49 years,105.0,63.0,Non-smoker,D6,1-50 number of beds,66,Unfixed,Fixed,Drug2,Drug10+Drug2,0
1391,MB1392,2015-12-09,2017-09-20,45.221081,Male,35 – 49 years,NaN,NaN,NaN,D1,More then 450 Number of beds,21,Unfixed,Unfixed,Drug2,Drug1+Drug2,0
1392,MB1393,2010-04-22,2011-01-01,45.253936,Male,35 – 49 years,122.0,83.0,NaN,D6,1-50 number of beds,8,Unfixed,Unfixed,Drug3,Drug3+Drug4+Drug2,0
1393,MB1394,2016-12-28,2017-08-22,54.360027,Female,50 - 64 years,124.0,82.0,Non-smoker,D6,1-50 number of beds,8,Unfixed,Unfixed,Drug3,Drug3,0
1394,MB1395,2009-07-05,2011-11-06,56.542094,Male,50 - 64 years,142.0,108.0,NaN,D6,1-50 number of beds,28,Unfixed,Unfixed,Drug3,Drug3,0
1395,MB1396,2015-10-21,2016-03-16,50.171116,Male,50 - 64 years,107.0,78.0,Non-smoker,D1,More then 450 Number of beds,5,Fixed,Fixed,Drug9,Drug1+Drug9+Drug2,0
1396,MB1397,2011-05-20,2011-10-20,40.917180,Male,35 – 49 years,134.0,86.0,Current smoker,D2,1-50 number of beds,5,Unfixed,Unfixed,Drug2,Drug3+Drug2,1
1397,MB1398,2015-04-24,2016-05-13,61.174538,Female,50 - 64 years,94.0,60.0,Non-smoker,D1,1-50 number of beds,13,Unfixed,Unfixed,Drug3,Drug3+Drug4,0
1398,MB1399,2014-04-05,2017-08-27,42.121834,Male,35 – 49 years,110.0,72.0,Current smoker,D1,1-50 number of beds,41,Unfixed,Fixed,Drug2,Drug4+Drug10,1
1399,MB1400,2017-08-26,2017-09-24,39.767283,Male,35 – 49 years,129.0,92.0,Non-smoker,D6,1-50 number of beds,1,Unfixed,Fixed,Drug2,Drug10+Drug2,0

In [5]:
data.shape

(1400, 17)

In [6]:
data.dtypes

patient_id                      object
line1stdate             datetime64[ns]
line2stdate             datetime64[ns]
age                            float64
gender                          object
agegroup                        object
sbpn                           float64
dbpn                           float64
smokingstatus                   object
Diseasecode                     object
hospitalsize                    object
durationofline1                  int64
line1drugcombination            object
line2drugcombination            object
line1drugs                      object
line2drugs                      object
curestatus                       int64
dtype: object

# missing value treatment

In [7]:
len(data[data.smokingstatus.isnull()])

466

In [8]:
len(data[data.dbpn.isnull()])

363

In [9]:
len(data[data.sbpn.isnull()])

363

In [10]:
data.isnull().sum()

patient_id                0
line1stdate               0
line2stdate               0
age                       0
gender                    0
agegroup                  0
sbpn                    363
dbpn                    363
smokingstatus           466
Diseasecode               0
hospitalsize              0
durationofline1           0
line1drugcombination      0
line2drugcombination      0
line1drugs                0
line2drugs                0
curestatus                0
dtype: int64

In [11]:
pd.crosstab(data.gender, data.smokingstatus)

smokingstatus  Current smoker  Non-smoker
gender
Female                     21         312
Male                      168         428
Malee                       4           1

In [12]:
data[data.gender=="Malee"]

,patient_id,line1stdate,line2stdate,age,gender,agegroup,sbpn,dbpn,smokingstatus,Diseasecode,hospitalsize,durationofline1,line1drugcombination,line2drugcombination,line1drugs,line2drugs,curestatus
15,MB0016,2015-12-20,2016-10-01,50.001369,Malee,50 - 64 years,109.0,71.0,Current smoker,D6,1-50 number of beds,9,Unfixed,Unfixed,Drug3,Drug3+Drug2,0
39,MB0040,2014-09-19,2015-03-20,52.665298,Malee,50 - 64 years,136.0,92.0,Current smoker,D1,351-450 number of beds,6,Unfixed,Unfixed,Drug3,Drug3+Drug2,0
870,MB0871,2017-01-22,2017-04-02,71.008898,Malee,≥ 65 years,151.0,88.0,Current smoker,D1,More then 450 Number of beds,2,Unfixed,Unfixed,Drug4,Drug4+Drug2,1
1012,MB1013,2014-03-20,2015-09-29,43.917864,Malee,35 – 49 years,102.0,60.0,Non-smoker,D3,1-50 number of beds,18,Fixed,Fixed,Drug9+Drug2,Drug1+Drug9,0
1304,MB1305,2015-02-19,2015-05-31,61.837098,Malee,50 - 64 years,109.0,61.0,Current smoker,D2,1-50 number of beds,3,Unfixed,Unfixed,Drug2,Drug3+Drug2,0

In [13]:
def getname(name):
    title_group = {'Malee':'Male',"Male":"Male","Female":"Female"}  
    return title_group[name]
data['gender']=data.gender.map(lambda x : getname(x))

In [14]:
data['gender'].value_counts()

Male      806
Female    594
Name: gender, dtype: int64

In [15]:
pd.crosstab(data.gender, data.smokingstatus)

smokingstatus  Current smoker  Non-smoker
gender
Female                     21         312
Male                      172         429

In [16]:
#filling the smokingstatus

In [17]:
data.groupby('gender')['smokingstatus'].value_counts()

gender  smokingstatus
Female  Non-smoker        312
        Current smoker     21
Male    Non-smoker        429
        Current smoker    172
Name: smokingstatus, dtype: int64

In [18]:
data['smokingstatus'].fillna(data['smokingstatus'].value_counts().index[0],inplace=True)
data.head()

,patient_id,line1stdate,line2stdate,age,gender,agegroup,sbpn,dbpn,smokingstatus,Diseasecode,hospitalsize,durationofline1,line1drugcombination,line2drugcombination,line1drugs,line2drugs,curestatus
0,MB0001,2010-06-19,2010-07-19,26.746064,Male,20 – 34 years,109.0,63.0,Non-smoker,D1,More then 450 Number of beds,1,Unfixed,Unfixed,Drug2,Drug3+Drug2,0
1,MB0002,2014-12-19,2015-02-19,54.332649,Male,50 - 64 years,119.0,87.0,Current smoker,D6,1-50 number of beds,2,Unfixed,Unfixed,Drug3,Drug3+Drug2,1
2,MB0003,2011-07-20,2011-09-20,47.249829,Female,35 – 49 years,110.0,64.0,Non-smoker,D6,1-50 number of beds,2,Unfixed,Unfixed,Drug3,Drug3+Drug2,1
3,MB0004,2017-07-29,2017-08-05,63.028063,Female,50 - 64 years,140.0,84.0,Non-smoker,D2,1-50 number of beds,0,Unfixed,Unfixed,Drug5,Drug1+Drug5,1
4,MB0005,2010-10-19,2014-03-19,48.082136,Female,35 – 49 years,157.0,96.0,Non-smoker,D6,More then 450 Number of beds,41,Unfixed,Unfixed,Drug3,Drug3+Drug2,0

In [19]:
#data["smokingstatus"].fillna(data.groupby("gender")["smokingstatus"].transform("mode"), inplace=True)

In [20]:
data[data.smokingstatus.isnull()]

Empty DataFrame
Columns: [patient_id, line1stdate, line2stdate, age, gender, agegroup, sbpn, dbpn, smokingstatus, Diseasecode, hospitalsize, durationofline1, line1drugcombination, line2drugcombination, line1drugs, line2drugs, curestatus]
Index: []

In [21]:
pd.crosstab(data.agegroup, data.smokingstatus)

smokingstatus  Current smoker  Non-smoker
agegroup
20 – 34 years               8          89
35 – 49 years              95         527
50 - 64 years              85         499
≥ 65 years                  5          92

In [22]:
pd.crosstab(data.line1drugcombination, data.smokingstatus)

smokingstatus         Current smoker  Non-smoker
line1drugcombination
Fixed                             13          70
Unfixed                          180        1137

# insterted based on conditions

In [23]:
age_sbpn_median=data.groupby(['gender','agegroup']).sbpn.transform('median')
age_sbpn_median.head()

0    122.5
1    128.0
2    117.0
3    124.0
4    117.0
Name: sbpn, dtype: float64

In [24]:
data.sbpn.fillna(age_sbpn_median, inplace=True)

In [25]:
data[data.sbpn.isnull()]

Empty DataFrame
Columns: [patient_id, line1stdate, line2stdate, age, gender, agegroup, sbpn, dbpn, smokingstatus, Diseasecode, hospitalsize, durationofline1, line1drugcombination, line2drugcombination, line1drugs, line2drugs, curestatus]
Index: []

In [26]:
age_dbpn_median=data.groupby(['gender','agegroup']).dbpn.transform('median')
age_dbpn_median.head()

0    70.0
1    80.0
2    70.0
3    76.0
4    70.0
Name: dbpn, dtype: float64

In [27]:
data.dbpn.fillna(age_dbpn_median, inplace=True)

In [28]:
data.isnull().sum()

patient_id              0
line1stdate             0
line2stdate             0
age                     0
gender                  0
agegroup                0
sbpn                    0
dbpn                    0
smokingstatus           0
Diseasecode             0
hospitalsize            0
durationofline1         0
line1drugcombination    0
line2drugcombination    0
line1drugs              0
line2drugs              0
curestatus              0
dtype: int64

# models

In [29]:
data.dtypes

patient_id                      object
line1stdate             datetime64[ns]
line2stdate             datetime64[ns]
age                            float64
gender                          object
agegroup                        object
sbpn                           float64
dbpn                           float64
smokingstatus                   object
Diseasecode                     object
hospitalsize                    object
durationofline1                  int64
line1drugcombination            object
line2drugcombination            object
line1drugs                      object
line2drugs                      object
curestatus                       int64
dtype: object

In [30]:
df = data.drop(labels = "patient_id", axis = 1)
df.head()

,line1stdate,line2stdate,age,gender,agegroup,sbpn,dbpn,smokingstatus,Diseasecode,hospitalsize,durationofline1,line1drugcombination,line2drugcombination,line1drugs,line2drugs,curestatus
0,2010-06-19,2010-07-19,26.746064,Male,20 – 34 years,109.0,63.0,Non-smoker,D1,More then 450 Number of beds,1,Unfixed,Unfixed,Drug2,Drug3+Drug2,0
1,2014-12-19,2015-02-19,54.332649,Male,50 - 64 years,119.0,87.0,Current smoker,D6,1-50 number of beds,2,Unfixed,Unfixed,Drug3,Drug3+Drug2,1
2,2011-07-20,2011-09-20,47.249829,Female,35 – 49 years,110.0,64.0,Non-smoker,D6,1-50 number of beds,2,Unfixed,Unfixed,Drug3,Drug3+Drug2,1
3,2017-07-29,2017-08-05,63.028063,Female,50 - 64 years,140.0,84.0,Non-smoker,D2,1-50 number of beds,0,Unfixed,Unfixed,Drug5,Drug1+Drug5,1
4,2010-10-19,2014-03-19,48.082136,Female,35 – 49 years,157.0,96.0,Non-smoker,D6,More then 450 Number of beds,41,Unfixed,Unfixed,Drug3,Drug3+Drug2,0

In [31]:
df5 = df.apply(lambda x: x["line2drugs"].split("+"), axis=1)
df5.columns=["index","drugs"]
df5.head()

0    [Drug3, Drug2]
1    [Drug3, Drug2]
2    [Drug3, Drug2]
3    [Drug1, Drug5]
4    [Drug3, Drug2]
dtype: object

In [32]:
df["line2drugs_0"]=df5[3][1]
df.head()

,line1stdate,line2stdate,age,gender,agegroup,sbpn,dbpn,smokingstatus,Diseasecode,hospitalsize,durationofline1,line1drugcombination,line2drugcombination,line1drugs,line2drugs,curestatus,line2drugs_0
0,2010-06-19,2010-07-19,26.746064,Male,20 – 34 years,109.0,63.0,Non-smoker,D1,More then 450 Number of beds,1,Unfixed,Unfixed,Drug2,Drug3+Drug2,0,Drug5
1,2014-12-19,2015-02-19,54.332649,Male,50 - 64 years,119.0,87.0,Current smoker,D6,1-50 number of beds,2,Unfixed,Unfixed,Drug3,Drug3+Drug2,1,Drug5
2,2011-07-20,2011-09-20,47.249829,Female,35 – 49 years,110.0,64.0,Non-smoker,D6,1-50 number of beds,2,Unfixed,Unfixed,Drug3,Drug3+Drug2,1,Drug5
3,2017-07-29,2017-08-05,63.028063,Female,50 - 64 years,140.0,84.0,Non-smoker,D2,1-50 number of beds,0,Unfixed,Unfixed,Drug5,Drug1+Drug5,1,Drug5
4,2010-10-19,2014-03-19,48.082136,Female,35 – 49 years,157.0,96.0,Non-smoker,D6,More then 450 Number of beds,41,Unfixed,Unfixed,Drug3,Drug3+Drug2,0,Drug5

In [33]:
df["line2drugs_1"]=df5[0][1]
df.head(20)

,line1stdate,line2stdate,age,gender,agegroup,sbpn,dbpn,smokingstatus,Diseasecode,hospitalsize,durationofline1,line1drugcombination,line2drugcombination,line1drugs,line2drugs,curestatus,line2drugs_0,line2drugs_1
0,2010-06-19,2010-07-19,26.746064,Male,20 – 34 years,109.0,63.0,Non-smoker,D1,More then 450 Number of beds,1,Unfixed,Unfixed,Drug2,Drug3+Drug2,0,Drug5,Drug2
1,2014-12-19,2015-02-19,54.332649,Male,50 - 64 years,119.0,87.0,Current smoker,D6,1-50 number of beds,2,Unfixed,Unfixed,Drug3,Drug3+Drug2,1,Drug5,Drug2
2,2011-07-20,2011-09-20,47.249829,Female,35 – 49 years,110.0,64.0,Non-smoker,D6,1-50 number of beds,2,Unfixed,Unfixed,Drug3,Drug3+Drug2,1,Drug5,Drug2
3,2017-07-29,2017-08-05,63.028063,Female,50 - 64 years,140.0,84.0,Non-smoker,D2,1-50 number of beds,0,Unfixed,Unfixed,Drug5,Drug1+Drug5,1,Drug5,Drug2
4,2010-10-19,2014-03-19,48.082136,Female,35 – 49 years,157.0,96.0,Non-smoker,D6,More then 450 Number of beds,41,Unfixed,Unfixed,Drug3,Drug3+Drug2,0,Drug5,Drug2
5,2016-07-07,2016-08-27,71.797399,Female,≥ 65 years,120.5,69.5,Non-smoker,D6,1-50 number of beds,2,Unfixed,Unfixed,Drug2,Drug3+Drug2,0,Drug5,Drug2
6,2014-06-22,2015-11-29,56.175222,Male,50 - 64 years,123.0,82.0,Non-smoker,D2,1-50 number of beds,17,Unfixed,Unfixed,Drug2,Drug3+Drug2,1,Drug5,Drug2
7,2016-01-23,2016-04-16,58.513347,Female,50 - 64 years,124.0,76.0,Non-smoker,D6,1-50 number of beds,3,Fixed,Fixed,Drug9,Drug9+Drug2,0,Drug5,Drug2
8,2013-12-19,2015-12-30,51.000684,Male,50 - 64 years,128.0,80.0,Non-smoker,D6,1-50 number of beds,24,Fixed,Unfixed,Drug10,Drug3+Drug2,1,Drug5,Drug2
9,2016-11-29,2016-12-04,51.613963,Male,50 - 64 years,114.0,70.0,Non-smoker,D6,1-50 number of beds,0,Unfixed,Fixed,Drug3,Drug1+Drug9,0,Drug5,Drug2
10,2014-07-19,2017-01-26,48.249144,Male,35 – 49 years,134.0,88.0,Non-smoker,D2,1-50 number of beds,30,Unfixed,Unfixed,Drug2,Drug2,0,Drug5,Drug2
11,2013-03-21,2017-01-25,65.752225,Male,≥ 65 years,138.0,80.0,Non-smoker,D2,351-450 number of beds,46,Unfixed,Unfixed,Drug2,Drug2,1,Drug5,Drug2
12,2013-11-29,2014-09-13,40.279261,Male,35 – 49 years,107.0,59.0,Non-smoker,D1,351-450 number of beds,9,Unfixed,Fixed,Drug2,Drug9+Drug2,1,Drug5,Drug2
13,2012-09-04,2014-12-10,50.130048,Male,50 - 64 years,128.0,80.0,Non-smoker,D6,1-50 number of beds,27,Unfixed,Fixed,Drug2,Drug10+Drug2,0,Drug5,Drug2
14,2015-08-09,2017-08-06,51.222450,Female,50 - 64 years,141.0,86.0,Non-smoker,D6,1-50 number of beds,24,Unfixed,Unfixed,Drug3,Drug5+Drug3,1,Drug5,Drug2
15,2015-12-20,2016-10-01,50.001369,Male,50 - 64 years,109.0,71.0,Current smoker,D6,1-50 number of beds,9,Unfixed,Unfixed,Drug3,Drug3+Drug2,0,Drug5,Drug2
16,2016-06-04,2016-06-11,56.958248,Female,50 - 64 years,124.0,76.0,Non-smoker,D2,1-50 number of beds,0,Unfixed,Unfixed,Drug2,Drug3+Drug4+Drug2,0,Drug5,Drug2
17,2008-07-24,2008-11-25,36.095825,Female,35 – 49 years,117.0,70.0,Non-smoker,D1,1-50 number of beds,4,Unfixed,Unfixed,Drug3,Drug3+Drug2,1,Drug5,Drug2
18,2014-02-16,2017-02-05,56.410678,Male,50 - 64 years,128.0,88.0,Non-smoker,D6,1-50 number of beds,36,Unfixed,Unfixed,Drug3,Drug3+Drug2,1,Drug5,Drug2
19,2016-12-22,2017-01-12,55.427789,Female,50 - 64 years,131.0,84.0,Non-smoker,D1,1-50 number of beds,1,Unfixed,Fixed,Drug1,Drug1+Drug9,0,Drug5,Drug2

In [34]:
dff = df.drop(labels = "line2drugs", axis = 1)

In [35]:
dff.agegroup.unique()

array(['20 – 34 years', '50 - 64 years', '35 – 49 years', '≥ 65 years'],
      dtype=object)

In [36]:
def getname(name):
    title_group = {'20 – 34 years':0,'50 - 64 years':1,'35 – 49 years':2, '≥ 65 years':3}  
    return title_group[name]
dff['agegroup']=dff.agegroup.map(lambda x : getname(x))

In [37]:
dff.head()

,line1stdate,line2stdate,age,gender,agegroup,sbpn,dbpn,smokingstatus,Diseasecode,hospitalsize,durationofline1,line1drugcombination,line2drugcombination,line1drugs,curestatus,line2drugs_0,line2drugs_1
0,2010-06-19,2010-07-19,26.746064,Male,0,109.0,63.0,Non-smoker,D1,More then 450 Number of beds,1,Unfixed,Unfixed,Drug2,0,Drug5,Drug2
1,2014-12-19,2015-02-19,54.332649,Male,1,119.0,87.0,Current smoker,D6,1-50 number of beds,2,Unfixed,Unfixed,Drug3,1,Drug5,Drug2
2,2011-07-20,2011-09-20,47.249829,Female,2,110.0,64.0,Non-smoker,D6,1-50 number of beds,2,Unfixed,Unfixed,Drug3,1,Drug5,Drug2
3,2017-07-29,2017-08-05,63.028063,Female,1,140.0,84.0,Non-smoker,D2,1-50 number of beds,0,Unfixed,Unfixed,Drug5,1,Drug5,Drug2
4,2010-10-19,2014-03-19,48.082136,Female,2,157.0,96.0,Non-smoker,D6,More then 450 Number of beds,41,Unfixed,Unfixed,Drug3,0,Drug5,Drug2

In [38]:
dff.gender=pd.get_dummies(dff.gender)
dff.head()

,line1stdate,line2stdate,age,gender,agegroup,sbpn,dbpn,smokingstatus,Diseasecode,hospitalsize,durationofline1,line1drugcombination,line2drugcombination,line1drugs,curestatus,line2drugs_0,line2drugs_1
0,2010-06-19,2010-07-19,26.746064,0,0,109.0,63.0,Non-smoker,D1,More then 450 Number of beds,1,Unfixed,Unfixed,Drug2,0,Drug5,Drug2
1,2014-12-19,2015-02-19,54.332649,0,1,119.0,87.0,Current smoker,D6,1-50 number of beds,2,Unfixed,Unfixed,Drug3,1,Drug5,Drug2
2,2011-07-20,2011-09-20,47.249829,1,2,110.0,64.0,Non-smoker,D6,1-50 number of beds,2,Unfixed,Unfixed,Drug3,1,Drug5,Drug2
3,2017-07-29,2017-08-05,63.028063,1,1,140.0,84.0,Non-smoker,D2,1-50 number of beds,0,Unfixed,Unfixed,Drug5,1,Drug5,Drug2
4,2010-10-19,2014-03-19,48.082136,1,2,157.0,96.0,Non-smoker,D6,More then 450 Number of beds,41,Unfixed,Unfixed,Drug3,0,Drug5,Drug2

In [39]:
dff.smokingstatus=pd.get_dummies(dff.smokingstatus)

In [40]:
dff.line1drugcombination=pd.get_dummies(dff.line1drugcombination)

In [41]:
dff.line2drugcombination=pd.get_dummies(dff.line2drugcombination)

In [42]:
dff

,line1stdate,line2stdate,age,gender,agegroup,sbpn,dbpn,smokingstatus,Diseasecode,hospitalsize,durationofline1,line1drugcombination,line2drugcombination,line1drugs,curestatus,line2drugs_0,line2drugs_1
0,2010-06-19,2010-07-19,26.746064,0,0,109.0,63.0,0,D1,More then 450 Number of beds,1,0,0,Drug2,0,Drug5,Drug2
1,2014-12-19,2015-02-19,54.332649,0,1,119.0,87.0,1,D6,1-50 number of beds,2,0,0,Drug3,1,Drug5,Drug2
2,2011-07-20,2011-09-20,47.249829,1,2,110.0,64.0,0,D6,1-50 number of beds,2,0,0,Drug3,1,Drug5,Drug2
3,2017-07-29,2017-08-05,63.028063,1,1,140.0,84.0,0,D2,1-50 number of beds,0,0,0,Drug5,1,Drug5,Drug2
4,2010-10-19,2014-03-19,48.082136,1,2,157.0,96.0,0,D6,More then 450 Number of beds,41,0,0,Drug3,0,Drug5,Drug2
5,2016-07-07,2016-08-27,71.797399,1,3,120.5,69.5,0,D6,1-50 number of beds,2,0,0,Drug2,0,Drug5,Drug2
6,2014-06-22,2015-11-29,56.175222,0,1,123.0,82.0,0,D2,1-50 number of beds,17,0,0,Drug2,1,Drug5,Drug2
7,2016-01-23,2016-04-16,58.513347,1,1,124.0,76.0,0,D6,1-50 number of beds,3,1,1,Drug9,0,Drug5,Drug2
8,2013-12-19,2015-12-30,51.000684,0,1,128.0,80.0,0,D6,1-50 number of beds,24,1,0,Drug10,1,Drug5,Drug2
9,2016-11-29,2016-12-04,51.613963,0,1,114.0,70.0,0,D6,1-50 number of beds,0,0,1,Drug3,0,Drug5,Drug2
10,2014-07-19,2017-01-26,48.249144,0,2,134.0,88.0,0,D2,1-50 number of beds,30,0,0,Drug2,0,Drug5,Drug2
11,2013-03-21,2017-01-25,65.752225,0,3,138.0,80.0,0,D2,351-450 number of beds,46,0,0,Drug2,1,Drug5,Drug2
12,2013-11-29,2014-09-13,40.279261,0,2,107.0,59.0,0,D1,351-450 number of beds,9,0,1,Drug2,1,Drug5,Drug2
13,2012-09-04,2014-12-10,50.130048,0,1,128.0,80.0,0,D6,1-50 number of beds,27,0,1,Drug2,0,Drug5,Drug2
14,2015-08-09,2017-08-06,51.222450,1,1,141.0,86.0,0,D6,1-50 number of beds,24,0,0,Drug3,1,Drug5,Drug2
15,2015-12-20,2016-10-01,50.001369,0,1,109.0,71.0,1,D6,1-50 number of beds,9,0,0,Drug3,0,Drug5,Drug2
16,2016-06-04,2016-06-11,56.958248,1,1,124.0,76.0,0,D2,1-50 number of beds,0,0,0,Drug2,0,Drug5,Drug2
17,2008-07-24,2008-11-25,36.095825,1,2,117.0,70.0,0,D1,1-50 number of beds,4,0,0,Drug3,1,Drug5,Drug2
18,2014-02-16,2017-02-05,56.410678,0,1,128.0,88.0,0,D6,1-50 number of beds,36,0,0,Drug3,1,Drug5,Drug2
19,2016-12-22,2017-01-12,55.427789,1,1,131.0,84.0,0,D1,1-50 number of beds,1,0,1,Drug1,0,Drug5,Drug2
20,2017-07-22,2017-11-02,47.008898,1,2,126.0,67.0,0,D1,1-50 number of beds,3,0,0,Drug3,1,Drug5,Drug2
21,2015-05-13,2015-07-12,33.645448,0,0,122.5,70.0,0,D2,1-50 number of beds,2,0,0,Drug3,0,Drug5,Drug2
22,2015-10-23,2015-11-10,52.008214,0,1,120.0,90.0,1,D6,1-50 number of beds,1,0,0,Drug2,0,Drug5,Drug2
23,2012-03-19,2013-01-19,53.415469,0,1,124.0,81.0,1,D1,351-450 number of beds,10,0,0,Drug2,1,Drug5,Drug2
24,2009-10-19,2011-04-20,38.833676,1,2,117.0,70.0,0,D6,1-50 number of beds,18,0,0,Drug3,1,Drug5,Drug2
25,2013-07-26,2016-01-16,57.932923,1,1,140.0,87.0,0,D1,More then 450 Number of beds,30,0,0,Drug2,1,Drug5,Drug2
26,2014-09-04,2014-09-28,39.709788,1,2,160.0,100.0,0,D1,1-50 number of beds,1,0,0,Drug3,0,Drug5,Drug2
27,2015-09-19,2016-04-12,47.334702,1,2,118.0,71.0,0,D1,1-50 number of beds,7,0,0,Drug2,1,Drug5,Drug2
28,2016-04-22,2016-05-06,66.507871,1,3,120.5,69.5,0,D2,1-50 number of beds,0,0,1,Drug2,0,Drug5,Drug2
29,2016-04-26,2017-09-26,50.351814,0,1,134.0,76.0,0,D6,1-50 number of beds,17,0,0,Drug2,1,Drug5,Drug2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1370,2016-07-30,2017-02-03,62.611910,0,1,140.0,100.0,0,D2,1-50 number of beds,6,0,0,Drug2,0,Drug5,Drug2
1371,2016-09-22,2016-09-30,60.925394,1,1,124.0,76.0,0,D1,1-50 number of beds,0,0,0,Drug2,0,Drug5,Drug2
1372,2017-09-05,2017-09-07,30.795346,0,0,122.5,70.0,0,D6,More then 450 Number of beds,0,1,0,Drug9,0,Drug5,Drug2
1373,2015-07-29,2017-05-18,41.941136,0,2,120.0,74.0,0,D6,1-50 number of beds,22,0,1,Drug2,0,Drug5,Drug2
1374,2015-07-26,2016-03-17,53.018480,0,1,138.0,83.0,0,D1,More then 450 Number of beds,8,0,0,Drug6,0,Drug5,Drug2
1375,2014-09-19,2016-01-30,41.169062,1,2,96.0,56.0,0,D1,1-50 number of beds,16,0,1,Drug3,0,Drug5,Drug2
1376,2014-12-19,2015-02-19,56.334018,0,1,118.0,57.0,0,D1,1-50 number of beds,2,0,0,Drug3,0,Drug5,Drug2
1377,2011-05-20,2011-09-20,44.246407,0,2,112.0,75.0,0,D2,More then 450 Number of beds,4,0,0,Drug2,0,Drug5,Drug2
1378,2016-08-14,2017-08-09,60.818617,0,1,116.0,77.0,0,D1,1-50 number of beds,12,0,0,Drug2,1,Drug5,Drug2
1379,2014-09-09,2017-06-06,64.309377,0,1,146.0,72.0,0,D2,1-50 number of beds,33,0,0,Drug2,1,Drug5,Drug2
1380,2013-09-11,2016-11-01,40.558522,0,2,129.0,89.0,1,D6,1-50 number of beds,38,0,0,Drug2,0,Drug5,Drug2
1381,2011-08-20,2013-05-19,52.668036,1,1,124.0,76.0,0,D4,251-350 number of beds,21,0,0,Drug3+Drug2,0,Drug5,Drug2
1382,2016-12-04,2017-05-04,40.208077,0,2,132.0,74.0,1,D1,1-50 number of beds,5,0,0,Drug2,0,Drug5,Drug2
1383,2013-12-28,2014-04-30,53.357974,0,1,112.0,75.0,0,D6,1-50 number of beds,4,0,1,Drug2,0,Drug5,Drug2
1384,2012-10-19,2016-08-10,43.252567,0,2,122.0,77.0,0,D6,1-50 number of beds,46,0,1,Drug2,0,Drug5,Drug2
1385,2015-12-24,2016-12-03,65.514031,1,3,120.5,69.5,0,D6,1-50 number of beds,11,0,0,Drug2,0,Drug5,Drug2
1386,2016-01-01,2016-01-23,51.786448,1,1,124.0,76.0,0,D2,1-50 number of beds,1,0,0,Drug2,0,Drug5,Drug2
1387,2017-07-19,2017-09-06,35.082820,0,2,122.0,77.0,0,D6,151-250 number of beds,2,1,1,Drug9,0,Drug5,Drug2
1388,2016-03-23,2016-11-15,40.172485,0,2,106.0,69.0,0,D6,1-50 number of beds,8,0,0,Drug2,0,Drug5,Drug2
1389,2012-03-02,2017-03-19,35.200548,0,2,123.0,82.0,0,D1,1-50 number of beds,61,0,0,Drug3,0,Drug5,Drug2
1390,2009-03-19,2014-09-19,47.915127,1,2,105.0,63.0,0,D6,1-50 number of beds,66,0,1,Drug2,0,Drug5,Drug2
1391,2015-12-09,2017-09-20,45.221081,0,2,122.0,77.0,0,D1,More then 450 Number of beds,21,0,0,Drug2,0,Drug5,Drug2
1392,2010-04-22,2011-01-01,45.253936,0,2,122.0,83.0,0,D6,1-50 number of beds,8,0,0,Drug3,0,Drug5,Drug2
1393,2016-12-28,2017-08-22,54.360027,1,1,124.0,82.0,0,D6,1-50 number of beds,8,0,0,Drug3,0,Drug5,Drug2
1394,2009-07-05,2011-11-06,56.542094,0,1,142.0,108.0,0,D6,1-50 number of beds,28,0,0,Drug3,0,Drug5,Drug2
1395,2015-10-21,2016-03-16,50.171116,0,1,107.0,78.0,0,D1,More then 450 Number of beds,5,1,1,Drug9,0,Drug5,Drug2
1396,2011-05-20,2011-10-20,40.917180,0,2,134.0,86.0,1,D2,1-50 number of beds,5,0,0,Drug2,1,Drug5,Drug2
1397,2015-04-24,2016-05-13,61.174538,1,1,94.0,60.0,0,D1,1-50 number of beds,13,0,0,Drug3,0,Drug5,Drug2
1398,2014-04-05,2017-08-27,42.121834,0,2,110.0,72.0,1,D1,1-50 number of beds,41,0,1,Drug2,1,Drug5,Drug2
1399,2017-08-26,2017-09-24,39.767283,0,2,129.0,92.0,0,D6,1-50 number of beds,1,0,1,Drug2,0,Drug5,Drug2

In [43]:
dff.Diseasecode.unique()

array(['D1', 'D6', 'D2', 'D4', 'D3', 'D5'], dtype=object)

In [44]:
def getname(name):
    title_group = {'D1':0,'D2':1,'D3':2, 'D4':3,'D5':4,'D6':5}  
    return title_group[name]
dff['Diseasecode']=dff.Diseasecode.map(lambda x : getname(x))

In [45]:
dff.hospitalsize.unique()

array(['More then 450 Number of beds', '1-50 number of beds',
       '351-450 number of beds', '151-250 number of beds',
       '51-150 number of beds', '251-350 number of beds'], dtype=object)

In [46]:
def getname(name):
    title_group = {'More then 450 Number of beds':0,'1-50 number of beds':1,'351-450 number of beds':2, '151-250 number of beds':3,'51-150 number of beds':4,'251-350 number of beds':5}  
    return title_group[name]
dff['hospitalsize']=dff.hospitalsize.map(lambda x : getname(x))

In [47]:
dff.line1drugs.unique()

array(['Drug2', 'Drug3', 'Drug5', 'Drug9', 'Drug10', 'Drug1',
       'Drug1+Drug2', 'Drug5+Drug3', 'Drug3+Drug2', 'Drug9+Drug2',
       'Drug3+Drug4', 'Drug3+Drug4+Drug2', 'Drug4', 'Drug3+Drug6+Drug2',
       'Drug6', 'Drug4+Drug2', 'Drug10+Drug2', 'Drug3+Drug6',
       'Drug3+Drug4+Drug6+Drug2', 'Drug5+Drug2', 'Drug4+Drug10',
       'Drug5+Drug4', 'Drug5+Drug4+Drug10', 'Drug1+Drug9+Drug2'],
      dtype=object)

In [48]:
def getname(name):
    title_group = {'Drug2':1, 'Drug3':2, 'Drug5':3, 'Drug9':4, 'Drug10':5, 'Drug1':6,
       'Drug1+Drug2':7, 'Drug5+Drug3':8, 'Drug3+Drug2':9, 'Drug9+Drug2':10,
       'Drug3+Drug4':11, 'Drug3+Drug4+Drug2':12, 'Drug4':13, 'Drug3+Drug6+Drug2':14,
       'Drug6':15, 'Drug4+Drug2':16, 'Drug10+Drug2':17, 'Drug3+Drug6':18,
       'Drug3+Drug4+Drug6+Drug2':19, 'Drug5+Drug2':20, 'Drug4+Drug10':21,
       'Drug5+Drug4':22, 'Drug5+Drug4+Drug10':23, 'Drug1+Drug9+Drug2':24}  
    return title_group[name]
dff['line1drugs']=dff.line1drugs.map(lambda x : getname(x))

In [49]:
dff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1400 entries, 0 to 1399
Data columns (total 17 columns):
line1stdate             1400 non-null datetime64[ns]
line2stdate             1400 non-null datetime64[ns]
age                     1400 non-null float64
gender                  1400 non-null uint8
agegroup                1400 non-null int64
sbpn                    1400 non-null float64
dbpn                    1400 non-null float64
smokingstatus           1400 non-null uint8
Diseasecode             1400 non-null int64
hospitalsize            1400 non-null int64
durationofline1         1400 non-null int64
line1drugcombination    1400 non-null uint8
line2drugcombination    1400 non-null uint8
line1drugs              1400 non-null int64
curestatus              1400 non-null int64
line2drugs_0            1400 non-null object
line2drugs_1            1400 non-null object
dtypes: datetime64[ns](2), float64(3), int64(6), object(2), uint8(4)
memory usage: 147.7+ KB

In [50]:
dff.line2drugs_0.unique()

array(['Drug5'], dtype=object)

In [51]:
pd.to_numeric(dff.age).head()

0    26.746064
1    54.332649
2    47.249829
3    63.028063
4    48.082136
Name: age, dtype: float64

In [52]:
features = dff[["age","gender","dbpn","sbpn","agegroup","smokingstatus","Diseasecode","hospitalsize","durationofline1","line1drugs"]]


label = dff["curestatus"]

In [53]:
### Splitting data for training and test 80/20 for our Base Model - Logistic Regression
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features, label, test_size=0.2, random_state=0)

In [54]:
X_train.shape

(1120, 10)

In [55]:
X_test.shape

(280, 10)

In [56]:
y_train.shape

(1120,)

In [57]:
y_test.shape

(280,)

In [58]:
from sklearn.tree import DecisionTreeClassifier

In [59]:
DTClassifier_5= DecisionTreeClassifier (max_depth=20, min_samples_split =3,criterion='gini',min_samples_leaf=2)
DTClassifier_5.fit(X_train,y_train)
predicted_labels = DTClassifier_5.predict(X_train)
accuracy_score_4 = accuracy_score(y_train, predicted_labels)
print(accuracy_score_4)

0.9285714285714286

In [61]:
y_true=y_train

In [62]:
y_pred=predicted_labels

In [63]:
from sklearn.metrics import confusion_matrix

In [75]:
m=confusion_matrix(y_true, y_pred)
m

array([[656,  17],
       [ 63, 384]], dtype=int64)

In [1]:
#fpr, tpr, thresholds=metrics.roc_curve(y_true,y_pred,pos_label=2)